# The following variables contains the files used by the different stages of the build process.
set(SAMV71_ISS_default_default_XC32_FILE_TYPE_assemble)
set_source_files_properties(${SAMV71_ISS_default_default_XC32_FILE_TYPE_assemble} PROPERTIES LANGUAGE ASM)

# For assembly files, add "." to the include path for each file so that .include with a relative path works
foreach(source_file ${SAMV71_ISS_default_default_XC32_FILE_TYPE_assemble})
        set_source_files_properties(${source_file} PROPERTIES INCLUDE_DIRECTORIES "$<PATH:NORMAL_PATH,$<PATH:REMOVE_FILENAME,${source_file}>>")
endforeach()

set(SAMV71_ISS_default_default_XC32_FILE_TYPE_assembleWithPreprocess)
set_source_files_properties(${SAMV71_ISS_default_default_XC32_FILE_TYPE_assembleWithPreprocess} PROPERTIES LANGUAGE ASM)

# For assembly files, add "." to the include path for each file so that .include with a relative path works
foreach(source_file ${SAMV71_ISS_default_default_XC32_FILE_TYPE_assembleWithPreprocess})
        set_source_files_properties(${source_file} PROPERTIES INCLUDE_DIRECTORIES "$<PATH:NORMAL_PATH,$<PATH:REMOVE_FILENAME,${source_file}>>")
endforeach()

set(SAMV71_ISS_default_default_XC32_FILE_TYPE_compile
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_3_CLI/app_cli.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_3_Network/app_network.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_3_USB/app_usb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_4_Alive/app_alive.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_4_Logging/app_logging.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/AppOS/App_x_Root/app_root.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/Boot/boot_manager.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M0_App/OS/os.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/EmbeddedCLI/CLI_Auth/simple_shield.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/EmbeddedCLI/CLI_Command/cli_command.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/EmbeddedCLI/CLI_Setup/cli_setup.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/EmbeddedCLI/CLI_Src/embedded_cli.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/FastIPC/fast_ipc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/dmesg/dmesg.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M1_SysApp/xlog/xlog.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M2_BSP/BSP_Board/bsp_board.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M2_BSP/UART/uart_dma.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M2_BSP/UART/uart_irq.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/components/dio/dummy/dummy_dio.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/components/i2c/dummy/dummy_i2c_io.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/components/i2c/i2c_io.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/components/spi/dummy/dummy_spi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/components/spi/spi_io.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/AD4114/ad4114.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/ADG1414BR/adg1414.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/AS3004204/as3004.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/BMP390/bmp390.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/LT8722/lt8722.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/MCP4902/mcp4902.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/RV3129/rv3129.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/ntc/ntc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/pca9685/pca9685.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/slf3s_flow/sl3s_flow.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M3_Driver/devices/tca6416/tca6416.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/Config/LwIP_Config/arch/sys_arch.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/Config/TinyUSB_Config/board_api.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/Config/TinyUSB_Config/usb_descriptors.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/croutine.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/event_groups.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/list.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/portable/GCC/ARM_CM7/r0p1/port.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/portable/MemMang/heap_4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/queue.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/stream_buffer.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/tasks.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/FreeRTOS/FreeRTOSv20240604-LTS/timers.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/api_lib.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/api_msg.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/err.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/if_api.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/netbuf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/netdb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/netifapi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/sockets.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/api/tcpip.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/altcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/altcp_alloc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/altcp_tcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/def.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/dns.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/inet_chksum.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/init.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ip.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/autoip.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/dhcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/etharp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/icmp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/igmp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/ip4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/ip4_addr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv4/ip4_frag.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/dhcp6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/ethip6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/icmp6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/inet6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/ip6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/ip6_addr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/ip6_frag.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/mld6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/ipv6/nd6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/mem.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/memp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/netif.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/pbuf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/raw.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/stats.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/sys.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/tcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/tcp_in.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/tcp_out.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/timeouts.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/core/udp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/bridgeif.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/bridgeif_fdb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ethernet.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/lowpan6.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/lowpan6_ble.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/lowpan6_common.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/auth.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/ccp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/chap-md5.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/chap-new.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/chap_ms.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/demand.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/eap.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/ecp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/eui64.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/fsm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/ipcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/ipv6cp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/lcp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/magic.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/mppe.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/multilink.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/polarssl/arc4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/polarssl/des.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/polarssl/md4.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/polarssl/md5.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/polarssl/sha1.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/ppp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/pppapi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/pppcrypt.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/pppoe.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/pppol2tp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/pppos.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/upap.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/utils.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/ppp/vj.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/slipif.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/LwIP/netif/zepif.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/Os/FreeRTOS/os_freertos.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/audio/audio_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/bth/bth_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/cdc/cdc_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/cdc/cdc_host.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/dfu/dfu_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/dfu/dfu_rt_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/hid/hid_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/hid/hid_host.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/midi/midi_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/midi/midi_host.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/msc/msc_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/msc/msc_host.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/mtp/mtp_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/net/ecm_rndis_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/net/ncm_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/usbtmc/usbtmc_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/vendor/vendor_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/vendor/vendor_host.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/class/video/video_device.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/common/tusb_fifo.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/device/usbd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/device/usbd_control.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/host/hub.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/host/usbh.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/analog/max3421/hcd_max3421.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/bridgetek/ft9xx/dcd_ft9xx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/chipidea/ci_fs/dcd_ci_fs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/chipidea/ci_hs/dcd_ci_hs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/chipidea/ci_hs/hcd_ci_hs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/dialog/da146xx/dcd_da146xx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/ehci/ehci.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/mentor/musb/dcd_musb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/mentor/musb/hcd_musb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/microchip/samx7x/dcd_samx7x.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/mindmotion/mm32/dcd_mm32f327x_otg.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nordic/nrf5x/dcd_nrf5x.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nuvoton/nuc120/dcd_nuc120.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nuvoton/nuc121/dcd_nuc121.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nuvoton/nuc505/dcd_nuc505.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nxp/khci/dcd_khci.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nxp/khci/hcd_khci.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nxp/lpc17_40/dcd_lpc17_40.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/nxp/lpc_ip3511/dcd_lpc_ip3511.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/ohci/ohci.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/raspberrypi/pio_usb/dcd_pio_usb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/raspberrypi/pio_usb/hcd_pio_usb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/raspberrypi/rp2040/dcd_rp2040.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/raspberrypi/rp2040/hcd_rp2040.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/raspberrypi/rp2040/rp2040_usb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/renesas/rusb2/dcd_rusb2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/renesas/rusb2/hcd_rusb2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/renesas/rusb2/rusb2_common.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/sony/cxd56/dcd_cxd56.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/st/stm32_fsdev/dcd_stm32_fsdev.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/st/stm32_fsdev/fsdev_common.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/st/stm32_fsdev/hcd_stm32_fsdev.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/st/typec/typec_stm32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/sunxi/dcd_sunxi_musb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/synopsys/dwc2/dcd_dwc2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/synopsys/dwc2/dwc2_common.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/synopsys/dwc2/hcd_dwc2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/template/dcd_template.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/template/hcd_template.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/ti/msp430x5xx/dcd_msp430x5xx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/valentyusb/eptri/dcd_eptri.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/wch/dcd_ch32_usbfs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/wch/dcd_ch32_usbhs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/portable/wch/hcd_ch32_usbfs.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/tusb.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M4_Middlewares/TinyUSB/typec/usbc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M5_Utils/DateTime/date_time.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M5_Utils/RingBuffer/ring_buffer.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M5_Utils/Tick/tick.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/M5_Utils/prnf/prnf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../Dev/System/ATSAMV71cm7_it.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/bsp/bsp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/exceptions.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/initialization.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/interrupts.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/libc_syscalls.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/afec/plib_afec0.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/afec/plib_afec1.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/clk/plib_clk.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/efc/plib_efc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/nvic/plib_nvic.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/pio/plib_pio.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/systick/plib_systick.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/tc/plib_tc3.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/uart/plib_uart2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/peripheral/usart/plib_usart2.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/startup_xc32.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/stdio/xc32_monitor.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/main.c")
set_source_files_properties(${SAMV71_ISS_default_default_XC32_FILE_TYPE_compile} PROPERTIES LANGUAGE C)
set(SAMV71_ISS_default_default_XC32_FILE_TYPE_compile_cpp)
set_source_files_properties(${SAMV71_ISS_default_default_XC32_FILE_TYPE_compile_cpp} PROPERTIES LANGUAGE CXX)
set(SAMV71_ISS_default_default_XC32_FILE_TYPE_link)
set(SAMV71_ISS_default_default_XC32_FILE_TYPE_bin2hex)

# The linker script used for the build.
set(SAMV71_ISS_default_LINKER_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/../../../My_MCC_Config/src/config/default/ATSAMV71Q21B.ld")
set(SAMV71_ISS_default_image_name "default.elf")
set(SAMV71_ISS_default_image_base_name "default")

# The output directory of the final image.
set(SAMV71_ISS_default_output_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../../out/SAMV71_ISS")

# The full path to the final image.
set(SAMV71_ISS_default_full_path_to_image ${SAMV71_ISS_default_output_dir}/${SAMV71_ISS_default_image_name})
